# Generated by Django 5.1.4 on 2025-01-12 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='profile_picture',
        ),
    ]
