# Generated by Django 5.1.4 on 2025-01-12 11:28

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0003_rename_image_profile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('uploaded_photo', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image')),
                ('tags', models.ManyToManyField(blank=True, related_name='photos', to='gallery_app.tag')),
            ],
        ),
    ]
